name: Docker Image CI/CD

on:
  schedule:
    - cron: '42 10 * * *' # Runs daily at 10:42 UTC
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: swconstruction
      REGISTRY: ${{ secrets.USE_GHCR == 'true' && 'ghcr.io' || 'docker.io' }}
      DOCKER_USER: ${{ secrets.USE_GHCR == 'true' && github.repository_owner || secrets.DOCKER_USERNAME || github.repository_owner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect OS and Architecture
        run: |
          echo "Operating System: $(uname -s)"
          echo "Architecture: $(uname -m)"
          case "$(uname -s)" in
            Linux) echo "✅ Linux OS detected" ;;
            Darwin) echo "✅ macOS detected" ;;
            *) echo "❌ Unsupported OS $(uname -s)"; exit 1 ;;
          esac
          case "$(uname -m)" in
            x86_64) echo "✅ x86_64 architecture detected" ;;
            arm64) echo "✅ arm64 architecture detected" ;;
            *) echo "❌ Unsupported architecture $(uname -m)"; exit 1 ;;
          esac

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log in to Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.USE_GHCR == 'true' && secrets.GITHUB_TOKEN || secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}

      - name: Debug Image Tag
        run: echo "${{ env.REGISTRY }}/${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}"

      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the Published Docker Image
        if: github.event_name != 'pull_request'
        env:
            TAGS: ${{ steps.meta.outputs.tags }}
            DIGEST: ${{ steps.build-and-push.outputs.digest }}
            COSIGN_EXPERIMENTAL: "true"
            run: |
                for attempt in 1 2 3; do
                if echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}; then
                  break
                fi
                echo "Cosign signing failed, retrying in 10 seconds... (attempt $attempt)"
                sleep 10
                done
